---
- hosts: ubuntu
  become: yes

  tasks:
    - name: Install Apache on Red Hat
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install Apache on Debian
      apt:
        name: apache2
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start and enable Apache service
      systemd:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: started
        enabled: yes

